
name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: src/webrcade

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}        

    - name: Clone dependencies
      run: |
        cd src && \
        chmod +x webrcade/dist-clone-deps.sh && \
        webrcade/dist-clone-deps.sh && \
        rm -rf webrcade/public/default-feed/content && \
        ( find . -type d -name ".git" ) | xargs rm -rf && \
        chmod +x webrcade/dist-version.sh && \
        webrcade/dist-version.sh "CI Build"
        
    - uses: actions/upload-artifact@v2
      with:
        name: webrcade-full-source
        path: src

    - name: Perform build
      run: |
        cd src/webrcade && \
        chmod +x dist.sh && \
        ./dist.sh && \
        chmod +x dist-package.sh && \
        ./dist-package.sh
        
    - uses: actions/upload-artifact@v2
      with:
        name: webrcade-dist
        path: src/webrcade/dist/package
